---
apiVersion: v1
kind: Namespace
metadata:
  name: mitmproxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mitmproxy
  namespace: mitmproxy
  labels:
    component: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      component: proxy
  template:
    metadata:
      labels:
        component: proxy
    spec:
      containers:
      - name: mitmproxy
        image: docker.io/mitmproxy/mitmproxy:6.0.2
        ports:
        - containerPort: 8080
          name: proxy-port
        resources:
          requests:
            memory: 256Mi
            cpu: 250m
          limits:
            memory: 256Mi
            cpu: 250m
        volumeMounts:
        - mountPath: /home/mitmproxy/.mitmproxy
          name: mitmproxy-state
      volumes:
        - name: mitmproxy-state
---
apiVersion: v1
kind: Service
metadata:
  name: mitmproxy
  namespace: mitmproxy
  labels:
    component: proxy
spec:
  ports:
  - port: 8080
    name: proxy-port
    targetPort: proxy-port
    protocol: TCP
  type: ClusterIP
  selector:
    component: proxy
