apiVersion: apps/v1
kind: Deployment
metadata:
  name: mitmproxy
  namespace: mitmproxy
spec:
  template:
    spec:
      containers:
      - name: mitmproxy
        args:
        - mitmdump
        - --verbose
        - --showhost
